apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-javaapp
  labels:
    app: my-javaapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-javaapp
  template:
    metadata:
      labels:
        app: my-javaapp
    spec:
      containers:
      - name: my-javaapp
        image: naveenkumarvelanati/javatestapp:33
        ports:
        - containerPort: 8081
